trigger:
- main 

pool:
  vmimage: "ubuntu-latest" 

stages:
- stage: BuildApp
  jobs:
  - job: BuildAndPush 
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Azure-demo'
        repository: 'adodemo12'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: '$(Build.BuildId)'
